name: Build tauri

on:
  push:
    tags:
      - v*

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.0.2
        run_install: true
    - name: install app dependencies and build it
      run: pnpm build
    - uses: jdukewich/tauri-action@fix-windows-bundling
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "PaletteWorks Editor v__VERSION__"
        releaseBody: "**Assets** からダウンロードしてインストールしてください。\n請從 **Assets** 文件下載安裝。\n**Assets** 에서 다운로드하여 설치하십시오.\nSee the **Assets** to download this version and install.\n**Assets**\n\n**Windows** .exe / .msi\n**Linux** .AppImage / .deb\n**macOS** .dmg\n\n**[Release Note](https://paletteworks.notion.site/PaletteWorks-Editor-7571ec4cffd4465f95ec0ff406bed54f)**"
        releaseDraft: true
        prerelease: false
